import { HabitTemplate } from '../types/index'

export const HABIT_TEMPLATES: HabitTemplate[] = [
  {
    id: 'morning-routine',
    name: 'Morning Routine',
    description: 'Start your day right with these energizing habits',
    category: 'Morning Routine',
    icon: '🌅',
    color: '#f59e0b',
    habits: [
      { name: 'Drink water', icon: '💧', frequency: 'daily', difficulty: 'easy' },
      { name: 'Morning meditation', icon: '🧘', frequency: 'daily', difficulty: 'medium' },
      { name: 'Exercise', icon: '🏃', frequency: 'daily', difficulty: 'medium' },
      { name: 'Healthy breakfast', icon: '🍎', frequency: 'daily', difficulty: 'easy' },
      { name: 'Plan the day', icon: '📝', frequency: 'daily', difficulty: 'easy' },
    ],
  },
  {
    id: 'fitness-health',
    name: 'Fitness & Health',
    description: 'Build a healthier, stronger you',
    category: 'Health',
    icon: '💪',
    color: '#22c55e',
    habits: [
      { name: 'Workout', icon: '🏋️', frequency: 'daily', difficulty: 'hard' },
      { name: 'Drink 8 glasses of water', icon: '💧', frequency: 'daily', difficulty: 'easy' },
      { name: 'Take vitamins', icon: '💊', frequency: 'daily', difficulty: 'easy' },
      { name: 'Track calories', icon: '🍽️', frequency: 'daily', difficulty: 'medium' },
      { name: '10,000 steps', icon: '🚶', frequency: 'daily', difficulty: 'medium' },
      { name: 'Stretch', icon: '🤸', frequency: 'daily', difficulty: 'easy' },
    ],
  },
  {
    id: 'productivity',
    name: 'Productivity Boost',
    description: 'Maximize your productivity and focus',
    category: 'Productivity',
    icon: '🎯',
    color: '#3b82f6',
    habits: [
      { name: 'Deep work session', icon: '💻', frequency: 'daily', difficulty: 'hard' },
      { name: 'Review goals', icon: '🎯', frequency: 'daily', difficulty: 'easy' },
      { name: 'Learn something new', icon: '📚', frequency: 'daily', difficulty: 'medium' },
      { name: 'Inbox zero', icon: '📧', frequency: 'daily', difficulty: 'medium' },
      { name: 'Plan tomorrow', icon: '📅', frequency: 'daily', difficulty: 'easy' },
    ],
  },
  {
    id: 'mindfulness',
    name: 'Mindfulness & Mental Health',
    description: 'Cultivate peace and mental clarity',
    category: 'Mindfulness',
    icon: '🧘',
    color: '#8b5cf6',
    habits: [
      { name: 'Meditation', icon: '🧘', frequency: 'daily', difficulty: 'medium' },
      { name: 'Gratitude journal', icon: '📔', frequency: 'daily', difficulty: 'easy' },
      { name: 'Deep breathing', icon: '🌬️', frequency: 'daily', difficulty: 'easy' },
      { name: 'Digital detox hour', icon: '📵', frequency: 'daily', difficulty: 'hard' },
      { name: 'Read for pleasure', icon: '📖', frequency: 'daily', difficulty: 'easy' },
    ],
  },
  {
    id: 'evening-routine',
    name: 'Evening Wind Down',
    description: 'End your day peacefully and prepare for rest',
    category: 'Evening Routine',
    icon: '🌙',
    color: '#6366f1',
    habits: [
      { name: 'Review the day', icon: '📝', frequency: 'daily', difficulty: 'easy' },
      { name: 'Prepare tomorrow\'s outfit', icon: '👔', frequency: 'daily', difficulty: 'easy' },
      { name: 'Skincare routine', icon: '🧴', frequency: 'daily', difficulty: 'easy' },
      { name: 'Read before bed', icon: '📚', frequency: 'daily', difficulty: 'easy' },
      { name: 'No screens 1hr before bed', icon: '📵', frequency: 'daily', difficulty: 'hard' },
      { name: 'Sleep by 10 PM', icon: '😴', frequency: 'daily', difficulty: 'medium' },
    ],
  },
  {
    id: 'creative',
    name: 'Creative Practice',
    description: 'Nurture your creative side',
    category: 'Creativity',
    icon: '🎨',
    color: '#ec4899',
    habits: [
      { name: 'Write/Journal', icon: '✍️', frequency: 'daily', difficulty: 'medium' },
      { name: 'Draw or sketch', icon: '🎨', frequency: 'daily', difficulty: 'medium' },
      { name: 'Practice instrument', icon: '🎵', frequency: 'daily', difficulty: 'hard' },
      { name: 'Creative reading', icon: '📚', frequency: 'daily', difficulty: 'easy' },
      { name: 'Brainstorm ideas', icon: '💡', frequency: 'daily', difficulty: 'easy' },
    ],
  },
  {
    id: 'social',
    name: 'Social & Relationships',
    description: 'Build stronger connections',
    category: 'Social',
    icon: '❤️',
    color: '#f43f5e',
    habits: [
      { name: 'Call a friend/family', icon: '📞', frequency: 'daily', difficulty: 'easy' },
      { name: 'Quality time with loved ones', icon: '👨‍👩‍👧', frequency: 'daily', difficulty: 'medium' },
      { name: 'Send a thoughtful message', icon: '💌', frequency: 'daily', difficulty: 'easy' },
      { name: 'Practice active listening', icon: '👂', frequency: 'daily', difficulty: 'medium' },
      { name: 'Express gratitude', icon: '🙏', frequency: 'daily', difficulty: 'easy' },
    ],
  },
]
